export const GET_WRITE_PLAN = 'WRITE_PLAN/GET_WRITE_PLAN' as const;
export const GET_WRITE_PLAN_SUCCESS = 'WRITE_PLAN/GET_WRITE_PLAN_SUCCESS' as const;
export const GET_WRITE_PLAN_FAILURE = 'WRITE_PLAN/GET_WRITE_PLAN_FAILURE' as const;
