export const GET_SAVE_PLAN = 'WRITE_PLAN/GET_SAVE_PLAN' as const;
export const GET_SAVE_PLAN_SUCCESS = 'WRITE_PLAN/GET_SAVE_PLAN_SUCCESS' as const;
export const GET_SAVE_PLAN_FAILURE = 'WRITE_PLAN/GET_SAVE_PLAN_FAILURE' as const;

export const CONTENT = 'WRITE_PLAN/CONTENT' as const;
export const GOAL = 'WRITE_PLAN/GOAL' as const;
export const INCLUDEOTHERS = 'WRITE_PLAN/INCLUDEOTHERS' as const;
export const INCLUDECODE = 'WRITE_PLAN/INCLUDECODE' as const;
export const INCLUDEOUTCOME = 'WRITE_PLAN/INCLUDEOUTCOME' as const;
export const INCLUDERESULTREPORT = 'WRITE_PLAN/INCLUDERESULTREPORT' as const;
export const PLANNEDENDDATE = 'WRITE_PLAN/PLANNEDENDDATE' as const;
export const PLANNEDSTARTDATE = 'WRITE_PLAN/PLANNEDSTARTDATE' as const;

export const PROJECTID = 'WRITE_PLAN/PROJECTID' as const;

export const GET_SUBMIT_PLAN = 'WRITE_PLAN/GET_SUBMIT_PLAN' as const;
export const GET_SUBMIT_PLAN_SUCCESS = 'WRITE_PLAN/GET_SUBMIT_PLAN_SUCCESS' as const;
export const GET_SUBMIT_PLAN_FAILURE = 'WRITE_PLAN/GET_SUBMIT_PLAN_FAILURE' as const;