export const CREATE_PROJECT = 'PROJECT/CREATE_PROJECT' as const;
export const CREATE_PROJECT_SUCCESS = 'PROJECT/CREATE_PROJECT_SUCCESS' as const;
export const CREATE_PROJECT_FAILURE = 'PROJECT/CREATE_PROJECT_FAILURE' as const;
