export const CREATE_PROJECT = 'PROJECT/CREATE_PROJECT' as const;
export const CREATE_PROJECT_SUCCESS = 'PROJECT/CREATE_PROJECT_SUCCESS' as const;
export const CREATE_PROJECT_FAILURE = 'PROJECT/CREATE_PROJECT_FAILURE' as const;

export const PROJECTNAME = 'PROJECT/CREATE_PROJECTNAME' as const;
export const PROJECTTYPE = 'PROJECT/CREATE_PROJECTTYPE' as const;
export const TEACHER = 'PROJECT/CREATE_TEACHER' as const;
export const TEAMNAME = 'PROJECT/CREATE_TEAMNAME' as const;
export const TECHSTACKS = 'PROJECT/CREATE_TECHSTACKS' as const;
export const FIELDLIST = 'PROJECT/CREATE_FIELDLIST' as const;
export const MEMBERLIST = 'PROJECT/CREATE_MEMBERLIST' as const;
export const ROLE = 'PROJECT/CREATE_ROLE' as const;

export const USERSLIST = 'PROJECT/GET_USERSLIST' as const;
export const USERSLIST_SUCCESS = 'PROJECT/GET_USERSLIST_SUCCESS' as const;
export const USERSLIST_FAILURE = 'PROJECT/GET_USERSLIST_FAILURE' as const;

export const DELETE_PROJECT = 'PROJECT/DELETE_PROJECT' as const;
export const DELETE_PROJECT_SUCCESS = 'PROJECT/DELETE_PROJECT_SUCCESS' as const;
export const DELETE_PROJECT_FAILURE = 'PROJECT/DELETE_PROJECT_FAILURE' as const;

export const MODIFY_PROJECT = 'PROJECT/MODIFY_PROJECT' as const;
export const MODIFY_PROJECT_SUCCESS = 'PROJECT/MODIFY_PROJECT_SUCCESS' as const;
export const MODIFY_PROJECT_FAILURE = 'PROJECT/MODIFY_PROJECT_FAILURE' as const;

export const MODIFY_URL = 'PROJECT/MODIFY_URL' as const;
export const MODIFY_URL_SUCCESS = 'PROJECT/MODIFY_URL_SUCCESS' as const;
export const MODIFY_URL_FAILURE = 'PROJECT/MODIFY_URL_FAILURE' as const;

export const DOCSURL = 'PROJECT/MODIFY_DOCSURL' as const;
export const GITHUB = 'PROJECT/MODIFY_GITHUB' as const;
export const SERVICEURL = 'PROJECT/MODIFY_SERVICEURL' as const;
