export const CREATE_PROJECT = 'PROJECT/CREATE_PROJECT' as const;
export const CREATE_PROJECT_SUCCESS = 'PROJECT/CREATE_PROJECT_SUCCESS' as const;
export const CREATE_PROJECT_FAILURE = 'PROJECT/CREATE_PROJECT_FAILURE' as const;

export const PROJECTNAME = 'PROJECT/CREATE_PROJECTNAME' as const;
export const PROJECTTYPE = 'PROJECT/CREATE_PROJECTTYPE' as const;
export const TEACHER = 'PROJECT/CREATE_TEACHER' as const;
export const TEAMNAME = 'PROJECT/CREATE_TEAMNAME' as const;
export const TECHSTACKS = 'PROJECT/CREATE_TECHSTACKS' as const;
export const FIELDLIST = 'PROJECT/CREATE_FIELDLIST' as const;
export const MEMBERLIST = 'PROJECT/CREATE_MEMBERLIST' as const;

export const USERSLIST = 'PROJECT/GET_USERSLIST' as const;
export const USERSLIST_SUCCESS = 'PROJECT/GET_USERSLIST_SUCCESS' as const;
export const USERSLIST_FAILURE = 'PROJECT/GET_USERSLIST_FAILURE' as const;

export const PROJECTDELETE = 'PROJECT/DELETE_PROJECTDELETE' as const;
export const PROJECTDELETE_SUCCESS = 'PROJECT/DELETE_PROJECTDELETE_SUCCESS' as const;
export const PROJECTDELETE_FAILURE = 'PROJECT/DELETE_PROJECTDELETE_FAILURE' as const;
