export const GET_PROJECT_CONTENTS = 'PROJECT/GET_PROJECT_CONTENTS' as const;
export const GET_PROJECT_CONTENTS_SUCCESS = 'PROJECT/GET_PROJECT_CONTENTS_SUCCESS' as const;
export const GET_PROJECT_CONTENTS_FAILURE = 'PROJECT/GET_PROJECT_CONTENTS_FAILURE' as const;

export const GET_MY_PROJECT_CONTENTS = 'MYPROJECT/GET_MY_PROJECT_CONTENTS' as const;
export const GET_MY_PROJECT_CONTENTS_SUCCESS = 'MYPROJECT/GET_MY_PROJECT_CONTENTS_SUCCESS' as const;
export const GET_MY_PROJECT_CONTENTS_FAILURE = 'MYPROJECT/GET_MY_PROJECT_CONTENTS_FAILURE' as const;

export const GET_PLAN_ACCEPTED_SUCCESS = 'MYPROJECT/GET_PLAN_ACCEPTED_SUCCESS' as const;
export const GET_PLAN_ACCEPTED_FAILURE = 'MYPROJECT/GET_PLAN_ACCEPTED_FAILURE' as const;
export const GET_REPORT_ACCEPTED_SUCCESS = 'MYPROJECT/GET_REPORT_ACCEPTED_SUCCESS' as const;
export const GET_REPORT_ACCEPTED_FAILURE = 'MYPROJECT/GET_REPORT_ACCEPTED_FAILURE' as const;
export const GET_PLAN_SUBMITTED_SUCCESS = 'MYPROJECT/GET_PLAN_SUBMITTED_SUCCESS' as const;
export const GET_PLAN_SUBMITTED_FAILURE = 'MYPROJECT/GET_PLAN_SUBMITTED_FAILURE' as const;
export const GET_REPORT_SUBMITTED_SUCCESS = 'MYPROJECT/GET_REPORT_SUBMITTED_SUCCESS' as const;
export const GET_REPORT_SUBMITTED_FAILURE = 'MYPROJECT/GET_REPORT_SUBMITTED_FAILURE' as const;
