export const GET_PROJECT_CONTENTS = 'PROJECT/GET_PROJECT_CONTENTS' as const;
export const GET_PROJECT_CONTENTS_SUCCESS = 'PROJECT/GET_PROJECT_CONTENTS_SUCCESS' as const;
export const GET_PROJECT_CONTENTS_FAILURE = 'PROJECT/GET_PROJECT_CONTENTS_FAILURE' as const;
