export const GET_SAVE_REPORT = 'WRITE_REPORT/GET_SAVE_REPORT' as const;
export const GET_SAVE_REPORT_SUCCESS = 'WRITE_REPORT/GET_SAVE_REPORT_SUCCESS' as const;
export const GET_SAVE_REPORT_FAILURE = 'WRITE_REPORT/GET_SAVE_REPORT_FAILURE' as const;

export const CONTENT = 'WRITE_REPORT/CONTENT' as const;
export const VIDEOURL = 'WRITE_REPORT/VIDEOURL' as const;
export const PROJECTID = 'WRITE_REPORT/PROJECTID' as const;

export const GET_SUBMIT_REPORT = 'WRITE_REPORT/GET_SUBMIT_REPORT' as const;
export const GET_SUBMIT_REPORT_SUCCESS = 'WRITE_REPORT/GET_SUBMIT_REPORT_SUCCESS' as const;
export const GET_SUBMIT_REPORT_FAILURE = 'WRITE_REPORT/GET_SUBMIT_REPORT_FAILURE' as const;